import type { FramePreset, ScreenGeometry } from './types';

const rect = (x: number, y: number, width: number, height: number, cornerRadius = 0.012): ScreenGeometry => ({
  topLeft: { x, y },
  topRight: { x: x + width, y },
  bottomRight: { x: x + width, y: y + height },
  bottomLeft: { x, y: y + height },
  cornerRadius,
});

export const DEFAULT_CUSTOM_GEOMETRY = rect(0.18, 0.075, 0.64, 0.711, 0.01);
export const DEFAULT_CUSTOM_GEOMETRIES = {
  desktop: DEFAULT_CUSTOM_GEOMETRY,
  tablet: rect(0.36, 0.055, 0.28, 0.722, 0.024),
  phone: rect(0.405, 0.040, 0.19, 0.734, 0.032),
} as const;

export const FRAME_PRESETS: FramePreset[] = [
  {
    id: 'custom',
    name: { tr: 'Özel Çerçeve', en: 'Custom Frame' },
    group: { tr: 'Özel ölçü', en: 'Custom size' },
    kind: 'custom',
    customVariant: 'desktop',
    aspectLabel: 'CUSTOM',
    viewport: { width: 1440, height: 900 },
    nativeResolution: 'CUSTOM',
    screen: DEFAULT_CUSTOM_GEOMETRY,
    finish: 'black', stand: 'studio', detail: 'none',
    appearance: { frameThickness: 14, frameCornerRadius: 24, screenCornerRadius: 16 },
    accent: '#f0f1ec',
    thumbnail: '◇',
  },
  {
    id: 'custom-tablet',
    name: { tr: 'Özel Tablet', en: 'Custom Tablet' },
    group: { tr: 'Özel ölçü', en: 'Custom size' },
    kind: 'tablet',
    customVariant: 'tablet',
    aspectLabel: 'CUSTOM',
    viewport: { width: 834, height: 1210 },
    nativeResolution: 'CUSTOM · TABLET',
    screen: DEFAULT_CUSTOM_GEOMETRIES.tablet,
    finish: 'black', stand: 'none', detail: 'tablet-camera',
    appearance: { frameThickness: 10, frameCornerRadius: 24, screenCornerRadius: 18 },
    accent: '#f0f1ec',
    thumbnail: '▯',
  },
  {
    id: 'custom-phone',
    name: { tr: 'Özel Telefon', en: 'Custom Phone' },
    group: { tr: 'Özel ölçü', en: 'Custom size' },
    kind: 'phone',
    customVariant: 'phone',
    aspectLabel: 'CUSTOM',
    viewport: { width: 402, height: 874 },
    nativeResolution: 'CUSTOM · PHONE',
    screen: DEFAULT_CUSTOM_GEOMETRIES.phone,
    finish: 'black', stand: 'none', detail: 'dynamic-island',
    appearance: { frameThickness: 8, frameCornerRadius: 32, screenCornerRadius: 26 },
    accent: '#f0f1ec',
    thumbnail: '▯',
  },
  {
    id: 'studio-16-9',
    name: { tr: '16:9', en: '16:9' },
    group: { tr: '16:9', en: '16:9' },
    kind: 'monitor',
    aspectLabel: '16:9',
    viewport: { width: 1920, height: 1080 },
    nativeResolution: '5120×2880 · 5K',
    screen: rect(0.15, 0.060, 0.70, 0.70),
    body: rect(0.143, 0.046, 0.714, 0.737),
    finish: 'silver', stand: 'studio', detail: 'display-camera',
    appearance: { frameThickness: 7, frameCornerRadius: 7, screenCornerRadius: 3 },
    parts: { stemWidth: 2.2, stemHeight: 16, baseWidth: 22, baseHeight: 3.2, baseRadius: 2 },
    accent: '#f4f4ef',
    thumbnail: '▭',
  },
  {
    id: 'editorial-16-10',
    name: { tr: '16:10', en: '16:10' },
    group: { tr: '16:10', en: '16:10' },
    kind: 'monitor',
    aspectLabel: '16:10',
    viewport: { width: 1600, height: 1000 },
    nativeResolution: '2560×1600 · 30″',
    screen: rect(0.18, 0.055, 0.64, 0.711),
    body: rect(0.174, 0.040, 0.652, 0.740),
    finish: 'graphite', stand: 'dell', detail: 'none',
    appearance: { frameThickness: 6, frameCornerRadius: 4, screenCornerRadius: 2 },
    parts: { stemWidth: 2.5, stemHeight: 7.5, baseWidth: 20, baseHeight: 2.4, baseRadius: 2 },
    accent: '#f4f4ef',
    thumbnail: '▭',
  },
  {
    id: 'panorama-21-9',
    name: { tr: '21:9', en: '21:9' },
    group: { tr: '21:9 ultrawide', en: '21:9 ultrawide' },
    kind: 'monitor',
    aspectLabel: '21:9',
    viewport: { width: 1720, height: 720 },
    nativeResolution: '3440×1440',
    screen: rect(0.09, 0.10, 0.82, 0.61),
    body: rect(0.080, 0.088, 0.840, 0.635),
    finish: 'black', stand: 'gaming', detail: 'none',
    appearance: { frameThickness: 7, frameCornerRadius: 9, screenCornerRadius: 5 },
    parts: { stemWidth: 2.4, stemHeight: 16, baseWidth: 27, baseHeight: 2.6, baseRadius: 2 },
    accent: '#f4f4ef',
    thumbnail: '▭',
  },
  {
    id: 'horizon-32-9',
    name: { tr: '32:9', en: '32:9' },
    group: { tr: '32:9 super ultrawide', en: '32:9 super ultrawide' },
    kind: 'monitor',
    aspectLabel: '32:9',
    viewport: { width: 3840, height: 1080 },
    nativeResolution: '7680×2160',
    screen: rect(0.06, 0.16, 0.88, 0.44),
    body: rect(0.050, 0.145, 0.900, 0.470),
    finish: 'black', stand: 'gaming', detail: 'none',
    appearance: { frameThickness: 7, frameCornerRadius: 10, screenCornerRadius: 5 },
    parts: { stemWidth: 2.6, stemHeight: 20, baseWidth: 28, baseHeight: 3, baseRadius: 2 },
    accent: '#f4f4ef',
    thumbnail: '▭',
  },
  {
    id: 'flat-4k',
    name: { tr: '16:9', en: '16:9' },
    group: { tr: 'Düz monitör', en: 'Flat monitor' },
    kind: 'monitor',
    aspectLabel: '16:9',
    viewport: { width: 1920, height: 1080 },
    nativeResolution: '6016×3384 · 6K',
    screen: rect(0.15, 0.065, 0.70, 0.70),
    body: rect(0.141, 0.050, 0.718, 0.733),
    finish: 'silver', stand: 'xdr', detail: 'none',
    appearance: { frameThickness: 8, frameCornerRadius: 4, screenCornerRadius: 1 },
    parts: { stemWidth: 3.6, stemHeight: 17, baseWidth: 18, baseHeight: 3.2, baseRadius: 2 },
    accent: '#f4f4ef',
    thumbnail: '▭',
  },
  {
    id: 'creator-laptop',
    name: { tr: '16:10', en: '16:10' },
    group: { tr: 'Laptop', en: 'Laptop' },
    kind: 'laptop',
    aspectLabel: '16:10',
    viewport: { width: 1728, height: 1117 },
    nativeResolution: '3456×2234 · 16.2″',
    screen: rect(0.20, 0.055, 0.60, 0.6895),
    body: rect(0.191, 0.035, 0.618, 0.732),
    finish: 'graphite', stand: 'laptop', detail: 'notch',
    appearance: { frameThickness: 8, frameCornerRadius: 10, screenCornerRadius: 7 },
    parts: { deckWidth: 62.2, deckHeight: 2.6 },
    accent: '#f4f4ef',
    thumbnail: '⌨',
  },
  {
    id: 'tablet-portrait',
    name: { tr: '417:605', en: '417:605' },
    group: { tr: 'Tablet', en: 'Tablet' },
    kind: 'tablet',
    aspectLabel: '1668:2420',
    viewport: { width: 834, height: 1210 },
    nativeResolution: '1668×2420 · 11″',
    screen: rect(0.3775, 0.055, 0.245, 0.632),
    body: rect(0.367, 0.038, 0.266, 0.660),
    finish: 'graphite', stand: 'none', detail: 'tablet-camera',
    appearance: { frameThickness: 8, frameCornerRadius: 24, screenCornerRadius: 18 },
    accent: '#f4f4ef',
    thumbnail: '▯',
  },
  {
    id: 'phone-pro',
    name: { tr: '201:437', en: '201:437' },
    group: { tr: 'Telefon', en: 'Phone' },
    kind: 'phone',
    aspectLabel: '402:874',
    viewport: { width: 402, height: 874 },
    nativeResolution: '1206×2622 · 6.3″',
    screen: rect(0.415, 0.044, 0.17, 0.657),
    body: rect(0.407, 0.029, 0.186, 0.690),
    finish: 'silver', stand: 'none', detail: 'dynamic-island',
    appearance: { frameThickness: 6, frameCornerRadius: 30, screenCornerRadius: 25 },
    accent: '#f4f4ef',
    thumbnail: '▯',
  },
];

export const getFrame = (id: string) => FRAME_PRESETS.find((frame) => frame.id === id) ?? FRAME_PRESETS[0];

export const groupFrames = (language: 'tr' | 'en') => {
  const groups = new Map<string, FramePreset[]>();
  FRAME_PRESETS.forEach((frame) => {
    const label = frame.group[language];
    groups.set(label, [...(groups.get(label) ?? []), frame]);
  });
  return [...groups.entries()];
};
